[package]
name = "ftp"
version = "0.1.0"
edition = "2024"

[dependencies]
obfstr = "0.4.4"
tasks = { path = "../../tasks" }
utils = { path = "../../utils" }
collector = { path = "../../collector" }
filesystem = { path = "../../filesystem" }